version: 2.1

jobs:
  build-application:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Project checkout"
          command: |
            sudo apt-get update
            sudo apt install git
            git clone https://github.com/AleksandrTkachov/FrameworkiumTemplate.git
            pwd
            ls -la
            sudo apt-get install openjdk-8-jdk -y
            sudo apt install maven -y
             

workflows:
  build-application-workflow:
    jobs:
      - build-application