version: 2.1

jobs:
  frameworkium-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Project checkout"
          command: "cat /etc/os-release"

workflows:
  frameworkium-tests-workflow:
    jobs:
      - frameworkium-tests