version: 2.1

jobs:
  frameworkium-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Project checkout"
          command: |
            sudo apt-get update
            sudo apt install git
            git clone https://github.com/AleksandrTkachov/FrameworkiumTemplate.git 

workflows:
  frameworkium-tests-workflow:
    jobs:
      - frameworkium-tests