version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: |
            cat /etc/os-release
            #wget https://github.com/bonigarcia/webdrivermanager/releases/download/webdrivermanager-5.3.1/webdrivermanager-5.3.1-fat.jar
            #java -jar webdrivermanager-5.3.1-fat.jar server



            # tar -xvzf geckodriver*
            # chmod +x geckodriver
            # ls -la
            # mv geckodriver /tmp
            # export PATH=$PATH:/tmp/geckodriver
            # echo $PATH
            #curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      # - run:
      #     name: Start Selenium
      #     command: |
      #       java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
      #     background: true
  ui-test:
      docker:
        - image: cimg/base:stable
      steps:
       - checkout
       - run:
             name: "Run UI test"
             command: |
               sudo apt-get update
               pwd
               ls -la
               sudo apt-get install openjdk-8-jdk -y
               sudo apt install maven -y
               mvn clean verify -f pom.xml -Dtest=SearchTests* 




      # steps:
      #   - checkout
      #   - run:
      #       name: "Run UI test"
      #       command: |
      #         sudo apt-get update
      #         pwd
      #         ls -la
      #         sudo apt-get install openjdk-8-jdk -y
      #         sudo apt install maven -y

      #         mvn clean verify -Dtest=SearchTests*    
      
        # - run:
        #     name: Start Selenium
        #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        #     background: true 
workflows:
  build-application-workflow:
    jobs:
    - ui-test