version: 2.1

jobs:
  frameworkium-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Project checkout"
          command: |
            git --version
            echo whoami
            cat /etc/os-release
            apt-get update 

workflows:
  frameworkium-tests-workflow:
    jobs:
      - frameworkium-tests