version: 2.1

orbs:
  saucectl: saucelabs/saucectl-run@2.0.0

jobs:
  test-cypress:
    docker:
      - image: cimg/node:lts
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.2
      - saucectl/saucectl-run

      # steps:
      #   - checkout
      #   - run:
      #       name: "Run UI test"
      #       command: |
      #         sudo apt-get update
      #         pwd
      #         ls -la
      #         sudo apt-get install openjdk-8-jdk -y
      #         sudo apt install maven -y

      #         mvn clean verify -Dtest=SearchTests*    
      
        # - run:
        #     name: Start Selenium
        #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        #     background: true 
workflows:
  build-application-workflow:
    jobs:
      - test-cypress