version: 2.1

jobs:
  build-application:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "git clone"
          command: |
            sudo apt-get update
            sudo apt install git
            git clone https://github.com/AleksandrTkachov/FrameworkiumTemplate.git
  api-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run API test"
          command: |
            sudo apt-get update
            pwd
            ls -la
            sudo apt-get install openjdk-8-jdk -y
            sudo apt install maven -y
            mvn clean verify -Dtest=api/tests/**.*
  ui-test:
      docker:
        - image: cimg/base:stable
      # steps:
      #   - checkout
      #   - run:
      #       name: "Run UI test"
      #       command: |
      #         sudo apt-get update
      #         pwd
      #         ls -la
      #         sudo apt-get install openjdk-8-jdk -y
      #         sudo apt install maven -y

      #         mvn clean verify -Dtest=SearchTests*    
      steps:
        - checkout
        - run: mkdir test-reports
        - run:
            name: Download Selenium
            command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
        # - run:
        #     name: Start Selenium
        #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        #     background: true 
        - run:
            name: "Run UI test"
            command: |
              sudo apt-get update
              pwd
              ls -la
              sudo apt-get install openjdk-8-jdk -y
              sudo apt install maven -y
              java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
              mvn clean verify -Dtest=SearchTests*   
workflows:
  build-application-workflow:
    jobs:
      - build-application
      - api-test
      - ui-test