version: 2.1
orbs:
  node: circleci/node@4.3.0
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  build-application:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "git clone"
          command: |
            sudo apt-get update
            sudo apt install git
            git clone https://github.com/AleksandrTkachov/FrameworkiumTemplate.git
            
  chrome:
    docker:
      - image: cimg/node:12.22-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run:
          name: Run TestCafe tests on headless Chrome
          command: npm run test:chrome:headless


  ui-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar
          background: true
 
      # steps:
      #   - checkout
      #   - run:
      #       name: "Run UI test"
      #       command: |
      #         sudo apt-get update
      #         pwd
      #         ls -la
      #         sudo apt-get install openjdk-8-jdk -y
      #         sudo apt install maven -y

      #         mvn clean verify -Dtest=SearchTests*    
      
        # - run:
        #     name: Start Selenium
        #     command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
        #     background: true 
workflows:
  build-application-workflow:
    jobs:
      - build-application
      - ui-test
      - chrome