version: 2.1

jobs:
  frameworkium-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Project checkout"
          command: "cat /etc/os-release"
      - run:
          name: "Build project"
          command: "sh 'mvn clean compile'"
      - run:
          name: "Test running"
          command: "sh 'mvn clean test'"

workflows:
  frameworkium-tests-workflow:
    jobs:
      - frameworkium-tests