version: 2.1

jobs:
  build-application:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "git clone"
          command: |
            sudo apt-get update
            sudo apt install git
            git clone https://github.com/AleksandrTkachov/FrameworkiumTemplate.git
  ui-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Run UI test"
          command: |
            sudo apt-get update
            pwd
            ls -la
            sudo apt-get install openjdk-8-jdk -y
            sudo apt install maven -y
            mvn clean verify -Dtest=SearchTests*
             

workflows:
  build-application-workflow:
    jobs:
      - build-application
      - ui-test